services:
  - type: web
    name: guuk-ai-backend
    env: python
    # Install all required Python dependencies listed in requirements.txt
    # Using uvicorn as the ASGI server to run the FastAPI application.
    # Configured to listen on all network interfaces (0.0.0.0) and port 10000.
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        value: ${FIREBASE_SERVICE_ACCOUNT_JSON}
      - key: FIREBASE_STORAGE_BUCKET
        value: guuk-ai-model2025.appspot.com
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      # The URL of the frontend application used for client-side interactions
      - key: FRONTEND_URL
        value: https://guuk-ai-model2025.vercel.app/
