services:
  - type: web
    name: https://guuk-ai-model2025-git-gatluaknyang-patch-1-guuk-ais-projects.vercel.app/
    env: python
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        value: ${FIREBASE_SERVICE_ACCOUNT_JSON}
      - key: FIREBASE_STORAGE_BUCKET
        value: guuk-ai-model2025.appspot.com
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: FRONTEND_URL
        value: https://guuk-ai-model2025.vercel.app/
