services:
  - type: web
    name: guuk-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        value: '{"type":"service_account",...}' # minified JSON here
      - key: FIREBASE_STORAGE_BUCKET
        value: guukai.appspot.com
      - key: SECRET_KEY
        value: your-secret-key
      - key: OPENAI_API_KEY
        value: your-openai-api-key
      - key: FRONTEND_URL
        value: https://your-frontend-url.vercel.app
